site_name: SpotMicroAI
nav:
    - Home: index.md
    - Build a SpotMicro: 
        - Collect All The Things!: gettingStarted.md
        - Assembly: assembly.md
    - Simulation: simulation.md
    - Kinematics: kinematic.md
    - Training: training.md
    - About: 
      - Credits: credits.md
      - Original Description: originalReadme.md
theme: readthedocs